org: visrutorg

app: serverless-v4-typescript

service: serverless-v4-typescript

plugins:
  - serverless-offline
  - serverless-iam-roles-per-function

build:
  esbuild:
    bundle: true
    minify: true

custom:
  serverless-offline:
    httpPort: 4000

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    CUSTOM_VAR: ${env:CUSTOM_VAR}

functions:
  hello:
    handler: functions/hello.handler
    events:
      - httpApi:
          path: /hello
          method: GET
    iamRoleStatementName: "hello-role"
    iamRoleStatements:
      - Sid: AllowLambdaInvocationAccess
        Effect: "Allow"
        Action:
          - "lambda:InvokeFunction"
        Resource:
          - "*"

  fun:
    handler: functions/fun.handler
