org: visrutorg

app: serverless-v4-typescript

service: serverless-v4-typescript

plugins:
  - serverless-offline
  - serverless-iam-roles-per-function

build:
  esbuild:
    bundle: true
    minify: true

custom:
  serverless-offline:
    httpPort: 4000

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    CUSTOM_VAR: ${env:CUSTOM_VAR}

resources:
  Resources:
    FunQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: funQueue.fifo
        FifoQueue: true
        ContentBasedDeduplication: true

  Outputs:
    FunQueueUrl:
      Value:
        Ref: FunQueue
      Export:
        Name: FunQueueUrl

functions:
  hello:
    handler: functions/hello.handler
    events:
      - httpApi:
          path: /hello
          method: GET
    iamRoleStatementsName: "hello-role"
    iamRoleStatements:
      - Sid: AllowLambdaSQSSendMessage
        Effect: "Allow"
        Action:
          - "sqs:SendMessage"
        Resource:
          - Fn::GetAtt: [FunQueue, Arn]
    environment:
      FUN_QUEUE_URL:
        Ref: FunQueue

  fun:
    handler: functions/fun.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - FunQueue
              - Arn
          batchSize: 1
